sudo: false
language: node_js
node_js: node
os:
  - linux
  - osx
branches:
  only:
    - master
script:
  - npm test
  - '[ "$TRAVIS_OS_NAME" != linux ] || npm run --silent verify-definitions -- $TRAVIS_COMMIT_RANGE'
notifications:
  email:
    on_success: never
